---
title: "Does your past define you? The role of previous visual experience in predicting new affective pictures and sounds"
subtitle: "Supplementary materials"
header-includes:
  - \setcounter{table}{0} 
  - \renewcommand*{\thetable}{S\arabic{table}}
  - \setcounter{figure}{0} 
  - \renewcommand*{\thefigure}{S\arabic{figure}}
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \AddToHook{cmd/section/before}{\clearpage}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
output: 
  bookdown::pdf_document2:
    latex_engine: lualatex
    keep_tex: true
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = "center",
                      fig.retina = 2,
                      dpi = 300)
options(knitr.kable.NA = '') # for NA values in tables
```

```{r packages, cache=FALSE}
library(tidyverse)
library(flextable)
library(here)
library(ftExtra)
devtools::load_all()
```

```{r functions}
get_element <- function(x){
    x %>% `[[`(1)
}

customize_table <- function(table, caption, font = 9){
  table %>% 
    fontsize(size = 8, part = "all") %>% 
    set_table_properties(layout = "autofit") %>% 
    set_caption(caption)
}
```

```{r loading-gen-data}
tab_stimuli <- read_rds(here("supplementary", "objects", "tab_stimuli.rds"))
tab_cond <- read_rds(here("supplementary", "objects", "tab_exp_cond.rds"))
```

```{r loading-data-visual}
mod_paper_visual <- read_rds(here("objects", "obj_visual", "mod_paper.rds"))
plot_paper_visual <- read_rds(here("objects", "obj_visual", "plot_paper.rds"))
anova_paper_visual <- read_rds(here("objects", "obj_visual", "anova_paper.rds"))
expl_visual <- read_rds(here("objects", "obj_visual", "expl_list.rds"))
dat_visual <- read_rds(here("data", "data_visual", "data_no_outlier.rds"))
```

```{r loading-data-auditory}
mod_paper_auditory <- read_rds(here("objects", "obj_auditory", "mod_paper.rds"))
plot_paper_auditory <- read_rds(here("objects", "obj_auditory", "plot_paper.rds"))
anova_paper_auditory <- read_rds(here("objects", "obj_auditory", "anova_paper.rds"))
expl_auditory <- read_rds(here("objects", "obj_auditory", "expl_list.rds"))
dat_auditory <- read_rds(here("data", "data_auditory", "data_no_outlier.rds"))
```

# Experiment 1

## Stimuli

```{r tableS1}
tab_stimuli$table_1 %>% set_caption(caption = "List of NAPS picture names used as S2s in Experiment 1, sorted by valence (Neg = negative, Neu = neutral).") %>% width(j = 2, 5, unit = "in") %>% fontsize(size = 8, part = "all") %>% knitr::knit_print()
```

```{r tableS2}
tab_stimuli$table_2 %>% customize_table(caption = "Means (M), standard deviations (SD), and results of two-tailed t-tests assuming unequal variance in luminance, contrast, complexity indices (i.e., JPEG size, entropy), and color space indices (i.e., LABL, LABA, LABB), referred to negative (Neg) and neutral (Neu) NAPS pictures employed as S2s in Experiment 1.") %>% knitr::knit_print()
```

```{r tableS3}
tab_cond %>% customize_table(caption = "Trials per experimental condition in the learning and test phases. For each phase and group (CG = certain group, UG = uncertain group) we report the S1 color (S1), the S2 valence (S2), the S1-S2 congruency (%) and the number of trials out of total (N). For the test phase we also report the predictive meaning of the cue according to new contingencies (Cue; Cueneg = cue preceding negative S2s, Cueneu = cue preceding neutral S2s), and the S2 congruency (Cong; Con = congruent, NCon = incongruent). Color-valence pairings were counterbalanced between subjects."
)
```

\newpage

## Time

### Block

```{r tableS4}
expl_visual$exp_mods_time$mods$fit_exp_block %>% 
  tidy_fit() %>% 
  mutate(mod = "fit_exp") %>% 
  prep_names_model() %>% 
  model_table(single_model = TRUE) %>% 
  customize_table(caption = "Results of exploratory LMMs investigating the effect of block (1 vs. 2), group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings in Experiment 1. We reported the unstandardized regression coefficients, standard errors (SE), 95% confidence intervals (CI), and the associated t-test.")
```

```{r tableS5}
expl_visual$exp_mods_time$mods$fit_exp_block %>% 
  tidy_anova() %>% 
  mutate(mod = "fit_exp") %>% 
  prep_names_anova() %>% 
  anova_table(single_model = TRUE) %>% 
  customize_table(caption = "Anova table of exploratory LMMs investigating the effect of block (1 vs. 2), group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings in Experiment 1.")
```

```{r figureS1, fig.cap="Box-plot of expectancy ratings in Experiment 1 according to the group (CG vs. UG), the block (1 vs. 2) and the cue ($cue_{neg}$ vs. $cue_{neu}$). Points represent the mean estimated value for each participant and condition."}

expl_visual$exp_mods_time$mods$fit_exp_block %>% 
  get_effects(y = exprating, workerId, group, block, s1_color) %>% 
  mutate(resp = case_when(resp == tolower("Exprating") ~ "Expectancy",
                          resp == tolower("Valrating") ~ "Valence",
                          resp == tolower("Arrating") ~ "Arousal",
                          TRUE ~ resp),
         resp = factor(resp, levels = c("Expectancy", "Valence", "Arousal")),
         block = paste("Block", block)) %>% 
  ggplot(aes(x = block, y = .mean, fill = group)) +
  geom_point(aes(color = group),
             position=position_jitterdodge(jitter.width = 0.4, jitter.height = 0)) +
  geom_boxplot(outlier.shape=NA, alpha = 0.7) +
  facet_wrap(~s1_color) +
  theme_paper() +
  scale_color_manual(name = "", values=c("#4DCA87", "#F09A0F")) +
  scale_fill_manual(name = "", values=c("#4DCA87", "#F09A0F")) +
  ylab("Rating (%)")
```
\newpage

### Trials

```{r figureS2, fig.cap="Relationship between trials, group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings for Experiment 1. For each subject and group a loess regression is fitted in order to represent the non-linear pattern. Furthermore, given the non-linearity we did not report the linear mixed-model analysis."}
dat_exp_visual <- dat_visual %>% filter(cond == "exp")

dat_exp_visual_summary <- dat_exp_visual %>% 
  group_by(trial_cond, s1_color, group) %>% 
  summarise(.mean = mean(exprating))

ggplot() +
  geom_line(data = dat_exp_visual,
            aes(x = trial_cond, y = exprating, group = workerId, color = group),
            stat="smooth",
            method = "loess",
            alpha = 0.15,
            size = 0.8) +
  geom_line(data = dat_exp_visual_summary,
            aes(x = trial_cond, y = .mean, color = group),
            stat="smooth",
            size = 2,
            method = "loess",
            alpha = 1) +
  facet_grid(~s1_color) +
  theme_paper() +
  xlab("Expectancy") +
  scale_y_continuous(breaks=seq(0, 100, 20), limits=c(-10, 115)) +
  scale_color_manual(name = "", values=c("#4DCA87", "#F09A0F")) +
  scale_fill_manual(name = "", values=c("#4DCA87", "#F09A0F")) +
  ylab("Expectancy (%)")
```

# Experiment 2

## Stimuli

```{r tableS6}
tab_stimuli$table_3 %>% set_caption(caption = "List of NAPS picture names used as S2s in Experiment 1, sorted by valence (Neg = negative, Neu = neutral).") %>% width(j = c(2,3), width = 2.5, unit = "in") %>% fontsize(size = 8, part = "all") %>% knitr::knit_print()
```

```{r tableS7}
tab_stimuli$table_4 %>% customize_table(caption = "Means (M), standard deviations (SD), and results of two-tailed t-tests assuming unequal variance in luminance, contrast, complexity indices (i.e., JPEG size, entropy), and color space indices (i.e., LABL, LABA, LABB) for affective pictures, and in physical properties (i.e., min dB, max dB, peak dB) for affective sounds, referred to negative (Neg) and neutral (Neu) NAPS pictures and IADS-2 sounds employed as S2s in Experiment 2.") %>% knitr::knit_print()
```

## Time

### Block

```{r tableS8}
expl_auditory$exp_mods_time$mods$fit_exp_block %>% 
  tidy_fit() %>% 
  mutate(mod = "fit_exp") %>% 
  prep_names_model() %>% 
  model_table(single_model = TRUE) %>% 
  customize_table(caption = "Results of exploratory LMMs investigating the effect of block (1 vs. 2), group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings in Experiment 2. We reported the unstandardized regression coefficients, standard errors (SE), 95% confidence intervals (CI), and the associated t-test.")
```

```{r tableS9}
expl_visual$exp_mods_time$mods$fit_exp_block %>% 
  tidy_anova() %>% 
  mutate(mod = "fit_exp") %>% 
  prep_names_anova() %>% 
  anova_table(single_model = TRUE) %>% 
  customize_table(caption = "Anova table of exploratory LMMs investigating the effect of block (1 vs. 2), group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings in Experiment 2.")
```

```{r figureS3, fig.cap="Box-plot of expectancy ratings in Experiment 2 according to the group (CG vs. UG), the block (1 vs. 2) and the cue ($cue_{neg}$ vs. $cue_{neu}$). Points represent the mean estimated value for each participant and condition."}
expl_auditory$exp_mods_time$mods$fit_exp_block %>% 
  get_effects(y = exprating, workerId, group, block, s1_color) %>% 
  mutate(resp = case_when(resp == tolower("Exprating") ~ "Expectancy",
                          resp == tolower("Valrating") ~ "Valence",
                          resp == tolower("Arrating") ~ "Arousal",
                          TRUE ~ resp),
         resp = factor(resp, levels = c("Expectancy", "Valence", "Arousal")),
         block = paste("Block", block)) %>% 
  ggplot(aes(x = block, y = .mean, fill = group)) +
  geom_point(aes(color = group),
             position=position_jitterdodge(jitter.width = 0.4, jitter.height = 0)) +
  geom_boxplot(outlier.shape=NA, alpha = 0.7) +
  facet_wrap(~s1_color) +
  theme_paper() +
  scale_color_manual(name = "", values=c("#4DCA87", "#F09A0F")) +
  scale_fill_manual(name = "", values=c("#4DCA87", "#F09A0F")) +
  ylab("Rating (%)")
```

\newpage

### Trials

```{r figureS4, fig.cap="Relationship between trials, group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings for Experiment 2. For each subject and group a loess regression is fitted in order to represent the non-linear pattern. Furthermore, given the non-linearity we did not reported the linear mixed-model analysis."}

dat_exp_auditory <- dat_auditory %>% filter(cond == "exp")

dat_exp_auditory_summary <- dat_exp_auditory %>% 
  group_by(trial_cond, s1_color, group) %>% 
  summarise(.mean = mean(exprating))

ggplot() +
  geom_line(data = dat_exp_auditory,
            aes(x = trial_cond, y = exprating, group = workerId, color = group),
            stat="smooth",
            method = "loess",
            alpha = 0.15,
            size = 0.8) +
  geom_line(data = dat_exp_auditory_summary,
            aes(x = trial_cond, y = .mean, color = group),
            stat="smooth",
            size = 2,
            method = "loess",
            alpha = 1) +
  facet_grid(~s1_color) +
  theme_paper() +
  scale_y_continuous(breaks=seq(0, 100, 20), limits=c(-10, 115)) +
  scale_color_manual(name = "", values=c("#4DCA87", "#F09A0F")) +
  scale_fill_manual(name = "", values=c("#4DCA87", "#F09A0F")) +
  ylab("Expectancy (%)")
```