% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Does your past define you? The role of previous visual experience in predicting new affective pictures and sounds},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\setcounter{table}{0}
\renewcommand*{\thetable}{S\arabic{table}}
\setcounter{figure}{0}
\renewcommand*{\thefigure}{S\arabic{figure}}
\usepackage{pdflscape}
\newcommand{\blandscape}{\begin{landscape}}
\newcommand{\elandscape}{\end{landscape}}
\AddToHook{cmd/section/before}{\clearpage}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{fontspec}
\usepackage{multirow}
\usepackage{multicol}
\usepackage{colortbl}
\usepackage{hhline}
\usepackage{longtable}
\usepackage{array}
\usepackage{hyperref}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Does your past define you? The role of previous visual experience in predicting new affective pictures and sounds}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Supplementary materials}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{experiment-1}{%
\section{Experiment 1}\label{experiment-1}}

\hypertarget{stimuli}{%
\subsection{Stimuli}\label{stimuli}}

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}

\begin{longtable}[c]{|p{0.97in}|p{5.00in}}

\caption{List of NAPS picture names used as S2s in Experiment 1, sorted by valence (Neg = negative, Neu = neutral).
}\label{tab:tableS1}\\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 0.97in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Valence}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 5in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NAPS\ pictures\ names}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\endfirsthead

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 0.97in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Valence}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 5in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NAPS\ pictures\ names}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 0.97in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{NEG}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 5in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{Animals\_001\_h;\ Animals\_024\_h;\ Animals\_025\_h;\ Animals\_027\_h;\ Animals\_033\_h;\ Animals\_038\_h;\ Animals\_054\_h;\ Animals\_068\_h;\ Animals\_071\_h;\ Animals\_074\_h;\ Animals\_077\_h;\ Animals\_078\_h;\ Faces\_146\_h;\ Faces\_150\_h;\ Faces\_152\_h;\ Faces\_170\_h;\ Faces\_271\_h;\ Faces\_272\_h;\ Faces\_285\_h;\ Faces\_290\_h;\ Faces\_291\_h;\ Faces\_293\_h;\ Faces\_294\_h;\ Faces\_302\_h;\ Landscapes\_002\_h;\ Landscapes\_004\_h;\ Landscapes\_005\_h;\ Landscapes\_007\_h;\ Landscapes\_010\_h;\ Landscapes\_011\_h;\ Landscapes\_014\_h;\ Landscapes\_017\_h;\ Landscapes\_022\_h;\ Landscapes\_026\_h;\ Landscapes\_139\_h;\ Landscapes\_177\_h;\ Objects\_001\_h;\ Objects\_002\_h;\ Objects\_003\_h;\ Objects\_007\_h;\ Objects\_011\_h;\ Objects\_022\_h;\ Objects\_125\_h;\ Objects\_132\_h;\ Objects\_139\_h;\ Objects\_149\_h;\ Objects\_283\_h;\ Objects\_285\_h;\ People\_001\_h;\ People\_008\_h;\ People\_020\_h;\ People\_022\_h;\ People\_118\_h;\ People\_127\_h;\ People\_136\_h;\ People\_140\_h;\ People\_200\_h;\ People\_215\_h;\ People\_225\_h;\ People\_226\_h}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 0.97in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{NEU}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 5in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{Animals\_109\_h;\ Animals\_114\_h;\ Animals\_122\_h;\ Animals\_125\_h;\ Animals\_126\_h;\ Animals\_136\_h;\ Animals\_165\_h;\ Animals\_169\_h;\ Animals\_170\_h;\ Animals\_197\_h;\ Animals\_202\_h;\ Animals\_206\_h;\ Faces\_184\_h;\ Faces\_186\_h;\ Faces\_188\_h;\ Faces\_282\_h;\ Faces\_304\_h;\ Faces\_314\_h;\ Faces\_316\_h;\ Faces\_326\_h;\ Faces\_329\_h;\ Faces\_331\_h;\ Faces\_335\_h;\ Faces\_343\_h;\ Landscapes\_009\_h;\ Landscapes\_041\_h;\ Landscapes\_048\_h;\ Landscapes\_050\_h;\ Landscapes\_089\_h;\ Landscapes\_100\_h;\ Landscapes\_107\_h;\ Landscapes\_127\_h;\ Landscapes\_143\_h;\ Landscapes\_149\_h;\ Landscapes\_163\_h;\ Landscapes\_172\_h;\ Objects\_025\_h;\ Objects\_033\_h;\ Objects\_041\_h;\ Objects\_069\_h;\ Objects\_075\_h;\ Objects\_078\_h;\ Objects\_079\_h;\ Objects\_103\_h;\ Objects\_254\_h;\ Objects\_262\_h;\ Objects\_263\_h;\ Objects\_270\_h;\ People\_069\_h;\ People\_089\_h;\ People\_099\_h;\ People\_101\_h;\ People\_109\_h;\ People\_153\_h;\ People\_162\_h;\ People\_167\_h;\ People\_173\_h;\ People\_178\_h;\ People\_194\_h;\ People\_250\_h}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}



\end{longtable}

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}

\begin{longtable}[c]{ccccccc}

\caption{Means (M), standard deviations (SD), and results of two-tailed t-tests assuming unequal variance in luminance, contrast, complexity indices (i.e., JPEG size, entropy), and color space indices (i.e., LABL, LABA, LABB), referred to negative (Neg) and neutral (Neu) NAPS pictures employed as S2s in Experiment 1.
}\label{tab:tableS2}\\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NEG}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NEU}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Measure}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{M}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{SD}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{M}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{SD}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{t(118)}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{p}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\endfirsthead

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NEG}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NEU}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Measure}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{M}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{SD}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{M}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{SD}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{t(118)}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{p}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{luminance}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{114.149}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{27.503}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{116.943}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{27.615}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.555}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.580}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{contrast}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{65.682}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{11.569}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{66.225}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{11.490}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.258}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.797}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{complexity}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{jpeg\_size}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{350,012.367}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{118,541.318}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{331,739.683}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{120,579.766}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.837}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.404}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{entropy}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{7.579}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.338}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{7.608}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.311}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.489}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.626}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{color\ space}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{LABL}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{47.078}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{11.035}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{48.411}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{11.090}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.660}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.511}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{LABA}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{1.684}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{4.600}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.541}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{7.901}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.969}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.335}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{LABB}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{7.444}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{9.766}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{7.492}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{11.416}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.025}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.980}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}



\end{longtable}

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}

\begin{longtable}[c]{ccccccccccc}

\caption{Trials per experimental condition in the learning and test phases. For each phase and group (CG = certain group, UG = uncertain group) we report the S1 color (S1), the S2 valence (S2), the S1-S2 congruency (\%) and the number of trials out of total (N). For the test phase we also report the predictive meaning of the cue according to new contingencies (Cue; Cueneg = cue preceding negative S2s, Cueneu = cue preceding neutral S2s), and the S2 congruency (Cong; Con = congruent, NCon = incongruent). Color-valence pairings were counterbalanced between subjects.
}\label{tab:tableS3}\\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{}}}}} & \multicolumn{4}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Learning\ Phase}}}}} & \multicolumn{6}{!{\color[HTML]{666666}\vrule width 1pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Test\ Phase}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Group}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{S1}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{S2}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{\%}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{N/40}}}}} & \multicolumn{1}{!{\color[HTML]{666666}\vrule width 1pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{S1}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Cue}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{S2}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Cong}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{\%}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{N/80}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\endfirsthead

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{}}}}} & \multicolumn{4}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Learning\ Phase}}}}} & \multicolumn{6}{!{\color[HTML]{666666}\vrule width 1pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Test\ Phase}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Group}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{S1}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{S2}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{\%}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{N/40}}}}} & \multicolumn{1}{!{\color[HTML]{666666}\vrule width 1pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{S1}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Cue}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{S2}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Cong}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{\%}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{N/80}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{666666}\vrule width 1pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neg}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neg}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{Con}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{75}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{30}}}} \\

\hhline{~~~~~~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{red}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neg}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{100}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{20}}}}} & \multicolumn{1}{!{\color[HTML]{666666}\vrule width 1pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{red}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neu}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neu}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{NCon}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{25}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{10}}}} \\

\hhline{~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{666666}\vrule width 1pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neg}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neg}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{NCon}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{25}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{10}}}} \\

\hhline{~~~~~~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-4}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{CG}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{blue}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neu}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{100}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{20}}}}} & \multicolumn{1}{!{\color[HTML]{666666}\vrule width 1pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{blue}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neu}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neu}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{Con}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{75}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{30}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neg}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{50}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{10}}}} & \multicolumn{1}{!{\color[HTML]{666666}\vrule width 1pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neg}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neg}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{Con}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{75}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{30}}}} \\

\hhline{~~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{red}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neu}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{50}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{10}}}} & \multicolumn{1}{!{\color[HTML]{666666}\vrule width 1pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{red}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neu}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neu}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{NCon}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{25}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{10}}}} \\

\hhline{~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neg}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{50}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{10}}}} & \multicolumn{1}{!{\color[HTML]{666666}\vrule width 1pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neg}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neg}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{NCon}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{25}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{10}}}} \\

\hhline{~~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-4}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{UG}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{blue}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neu}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{50}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{10}}}} & \multicolumn{1}{!{\color[HTML]{666666}\vrule width 1pt}>{}c}{\multirow[c]{-2}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{blue}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neu}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{neu}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{Con}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{75}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{30}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}



\end{longtable}

\newpage

\hypertarget{time}{%
\subsection{Time}\label{time}}

\hypertarget{block}{%
\subsubsection{Block}\label{block}}

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}

\begin{longtable}[c]{cccccccc}

\caption{Results of exploratory LMMs investigating the effect of block (1 vs. 2), group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings in Experiment 1. We reported the unstandardized regression coefficients, standard errors (SE), 95\% confidence intervals (CI), and the associated t-test.
}\label{tab:tableS4}\\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Parameter}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Estimate}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{SE}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{t}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{df}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{p}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{95\%\ CI}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\endfirsthead

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Parameter}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Estimate}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{SE}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{t}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{df}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{p}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{95\%\ CI}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Intercept}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{52.67}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.62}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{85.52}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{253.94}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.001}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{51.46}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{53.88}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{UG}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{CG}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-0.66}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.23}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-0.54}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{253.94}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.59}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-3.09}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.76}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{block}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{2}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{block}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.50}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.47}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.05}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{7,070.08}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.294}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-0.43}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.43}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{neg}}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{neu}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{24.59}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.91}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{12.89}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{208.45}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.001}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{20.83}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{28.36}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{group}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{x}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{block}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.16}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.95}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.22}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{7,070.08}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.222}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-0.70}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{3.02}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{x}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{group}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{23.88}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{3.82}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{6.26}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{208.45}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.001}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{16.35}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{31.40}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{block}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{x}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.84}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.95}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.94}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{7,083.16}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.052}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-0.02}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{3.70}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{group}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{x}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{block}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{x}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-8.77}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.90}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-4.62}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{7,083.16}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.001}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-12.49}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-5.05}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{σ}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{ID}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{6.99}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{σ}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{24.18}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{σ}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{residual}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{20.00}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}



\end{longtable}

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}

\begin{longtable}[c]{cccccc}

\caption{Anova table of exploratory LMMs investigating the effect of block (1 vs. 2), group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings in Experiment 1.
}\label{tab:tableS5}\\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Effect}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{SS}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Df}}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{num}}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Df}}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{den}}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{F}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{p}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\endfirsthead

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Effect}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{SS}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Df}}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{num}}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Df}}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{den}}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{F}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{p}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Group}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{2.20}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{183.07}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.01}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.941}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Block}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{441.38}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{7,070.08}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.10}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.294}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{76,327.03}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{183.02}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{190.74}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<\ 0.001}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Group\ x\ Block}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{597.69}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{7,070.08}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.49}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.222}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Group\ x\ Cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{11,137.28}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{183.02}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{27.83}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<\ 0.001}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Block\ x\ Cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1,509.38}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{7,083.16}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{3.77}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.052}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Group\ x\ Block\ x\ Cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{8,553.04}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{7,083.16}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{21.37}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<\ 0.001}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}



\end{longtable}

\begin{figure}

{\centering \includegraphics[width=1950px]{supplementary_files/figure-latex/figureS1-1} 

}

\caption{Box-plot of expectancy ratings in Experiment 1 according to the group (CG vs. UG), the block (1 vs. 2) and the cue ($cue_{neg}$ vs. $cue_{neu}$). Points represent the mean estimated value for each participant and condition.}\label{fig:figureS1}
\end{figure}
\newpage

\hypertarget{trials}{%
\subsubsection{Trials}\label{trials}}

\begin{figure}

{\centering \includegraphics[width=1950px]{supplementary_files/figure-latex/figureS2-1} 

}

\caption{Relationship between trials, group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings for Experiment 1. For each subject and group a loess regression is fitted using the ggplot package and the loess method in order to represent the non-linear pattern. Furthermore, given the non-linearity we did not report the linear mixed-model analysis.}\label{fig:figureS2}
\end{figure}

\hypertarget{discussion-experiment-1-exploratory-model-on-expectancy-ratings}{%
\subsection{Discussion (Experiment 1 exploratory model on expectancy ratings)}\label{discussion-experiment-1-exploratory-model-on-expectancy-ratings}}

Results of the exploratory model on expectancy ratings in Experiment 1 showed a significant three-way interaction between group, cue and block \(F(1, 7083) = 21.37\) ,\(p < 0.001)\). Post-hoc contrasts decomposing the interaction showed that in the CG expectancy ratings to cue\textsubscript{neg} became slightly less negative, even though not significantly, between block 1 and block 2 (\(block 1-2: 0.19\), \(SE = 0.90\), \(t(7081) = 0.22\), \(p = 0.83)\), while expectancy ratings to cue\textsubscript{neu} became more negative from block 1 to block 2 (\(block 1-2: -2.35\), \(SE = 0.90\), \(t(7081) = -2.62\), \(p = 0.009\)). In the UG, expectancy ratings to cue\textsubscript{neg} became more negative between block 1 and block 2 (\(block 1-2: -3.03\), \(SE = 1.00\), \(t(7073) = -3.04\), \(p = 0.002\)), while expectancy ratings to cue\textsubscript{neu} became less negative from block 1 to block 2 (\(block 1-2: 3.20\), \(SE = 1.00\), \(t(7073) = 3.21\), \(p = 0.001\)).
Thus, results suggest that both groups learn the new 75\% contingencies of the test phase, and they adapt their expectancy ratings accordingly. In fact, the CG shows progressively less extreme expectancy ratings as the test phase proceeds, proving that they transitioned from a more reliable predictive context (100\%, experienced during the learning phase, according to which they generate their expectancies in the first half of the test phase) to a new, less reliable context (75\%, experienced during the test phase, according to which they adapt their expectancies as the test phase proceeds). The UG, instead, shows progressively more extreme ratings as the test phase progresses, proving that they transitioned from a less reliable predictive context (50\%, experienced during the learning phase, according to which they generate their expectancies in the first half of the test phase) to a new, more reliable context (75\%, experienced during the test phase, according to which they adapt their expectancies as the test phase proceeds).

\hypertarget{experiment-2}{%
\section{Experiment 2}\label{experiment-2}}

\hypertarget{stimuli-1}{%
\subsection{Stimuli}\label{stimuli-1}}

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}

\begin{longtable}[c]{|p{0.97in}|p{2.50in}|p{2.50in}}

\caption{List of NAPS picture names used as S2s in Experiment 1, sorted by valence (Neg = negative, Neu = neutral).
}\label{tab:tableS6}\\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 0.97in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Valence}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 2.5in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NAPS\ pictures\ names}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 2.5in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{IADS-2\ sounds\ numbers}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\endfirsthead

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 0.97in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Valence}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 2.5in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NAPS\ pictures\ names}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 2.5in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{IADS-2\ sounds\ numbers}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 0.97in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{NEG}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 2.5in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{Animals\_074\_h,\ Animals\_077\_h,\ Animals\_078\_h,\ Animals\_024\_h,\ Faces\_293\_h,\ Faces\_290\_h,\ Faces\_302\_h,\ Faces\_152\_h,\ Landscapes\_139\_h,\ Landscapes\_005\_h,\ Landscapes\_026\_h,\ Landscapes\_002\_h,\ Objects\_139\_h,\ Objects\_125\_h,\ Objects\_149\_h,\ Objects\_003\_h,\ People\_226\_h,\ People\_022\_h,\ People\_140\_h,\ People\_127\_h}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 2.5in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{105,\ 106,\ 115,\ 116,\ 241,\ 242,\ 244,\ 255,\ 276,\ 277,\ 279,\ 283,\ 285,\ 286,\ 289,\ 290,\ 292,\ 293,\ 295,\ 296,\ 420,\ 422,\ 423,\ 424,\ 501,\ 502,\ 600,\ 611,\ 624,\ 625,\ 626,\ 703,\ 709,\ 711,\ 712,\ 713,\ 714,\ 719,\ 730,\ 732}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 0.97in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{NEU}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 2.5in+0\tabcolsep+0\arrayrulewidth}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{Animals\_170\_h,\ Animals\_206\_h,\ Animals\_125\_h,\ Animals\_109\_h,\ Faces\_304\_h,\ Faces\_316\_h,\ Faces\_331\_h,\ Faces\_326\_h,\ Landscapes\_127\_h,\ Landscapes\_149\_h,\ Landscapes\_163\_h,\ Landscapes\_107\_h,\ Objects\_262\_h,\ Objects\_254\_h,\ Objects\_263\_h,\ Objects\_078\_h,\ People\_194\_h,\ People\_099\_h,\ People\_173\_h,\ People\_101\_h}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{\raggedright}p{\dimexpr 2.5in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{107,\ 109,\ 113,\ 120,\ 132,\ 150,\ 152,\ 170,\ 171,\ 172,\ 206,\ 225,\ 254,\ 262,\ 270,\ 355,\ 360,\ 361,\ 363,\ 364,\ 365,\ 370,\ 374,\ 375,\ 377,\ 378,\ 400,\ 403,\ 601,\ 602,\ 610,\ 698,\ 704,\ 705,\ 716,\ 721,\ 724,\ 725,\ 726,\ 808}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}



\end{longtable}

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}

\begin{longtable}[c]{cccccccc}

\caption{Means (M), standard deviations (SD), and results of two-tailed t-tests assuming unequal variance in luminance, contrast, complexity indices (i.e., JPEG size, entropy), and color space indices (i.e., LABL, LABA, LABB) for affective pictures, and in physical properties (i.e., min dB, max dB, peak dB) for affective sounds, referred to negative (Neg) and neutral (Neu) NAPS pictures and IADS-2 sounds employed as S2s in Experiment 2.
}\label{tab:tableS7}\\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NEG}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NEU}}}}} & \multicolumn{3}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Measure}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{M}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{SD}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{M}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{SD}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{t}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{df}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{p}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\endfirsthead

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NEG}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{NEU}}}}} & \multicolumn{3}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{Measure}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{M}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{SD}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{M}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{SD}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{t}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{df}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{\textbf{p}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{luminance}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{110.232}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{23.168}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{121.242}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{24.168}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-1.471}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.150}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{contrast}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{65.834}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{10.017}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{61.919}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{10.617}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{1.199}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.238}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{jpeg\_size}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{345,480.200}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{115,725.462}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{357,945.550}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{111,068.563}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.348}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.730}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{entropy}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{7.623}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.399}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{7.663}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.216}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.394}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.695}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{LABL}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{45.552}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{9.136}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{50.539}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{9.667}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-1.677}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.102}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{LABA}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{2.089}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{4.294}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-1.576}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{10.822}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{1.408}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.167}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{LABB}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{5.316}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{5.992}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{6.630}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{15.278}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.358}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-7}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{38}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.722}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{min\ dB}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.673}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.058}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.657}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.094}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.916}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.362}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{max\ dB}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.668}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.052}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.681}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.116}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.638}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.526}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-~>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{peak\ amp\ dB}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-93.125}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{566.920}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-3.582}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{1.347}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{-0.999}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\multirow[c]{-3}{*}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{78}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{DejaVu Sans}{0.321}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}



\end{longtable}

\hypertarget{time-1}{%
\subsection{Time}\label{time-1}}

\hypertarget{block-1}{%
\subsubsection{Block}\label{block-1}}

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}

\begin{longtable}[c]{cccccccc}

\caption{Results of exploratory LMMs investigating the effect of block (1 vs. 2), group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings in Experiment 2. We reported the unstandardized regression coefficients, standard errors (SE), 95\% confidence intervals (CI), and the associated t-test.
}\label{tab:tableS8}\\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Parameter}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Estimate}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{SE}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{t}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{df}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{p}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{95\%\ CI}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\endfirsthead

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Parameter}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Estimate}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{SE}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{t}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{df}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{p}}}}} & \multicolumn{2}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{95\%\ CI}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Intercept}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{53.52}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.60}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{89.08}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{239.32}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.001}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{52.34}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{54.70}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{UG}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{CG}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.14}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.20}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.95}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{239.32}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.345}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-1.23}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{3.50}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{block}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{2}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{block}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-0.04}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.49}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-0.09}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{6,420.49}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.926}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-1.00}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.91}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{neg}}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{neu}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{17.99}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{2.10}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{8.59}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{185.89}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.001}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{13.86}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{22.13}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{group}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{x}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{block}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-1.20}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.97}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-1.23}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{6,420.49}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.219}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-3.11}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.71}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{x}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{group}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{10.87}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{4.19}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{2.59}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{185.89}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.01}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{2.60}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{19.13}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{block}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{x}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{5.70}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.97}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{5.86}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{6,445.98}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.001}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{3.79}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{7.61}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{group}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{x}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{block}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{x}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.89}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.95}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.46}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{6,445.98}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.649}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{-2.93}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{4.70}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{σ}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{ID}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{6.37}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{σ}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{25.57}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{σ}}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\ }}}\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{residual}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{19.57}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}c!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}



\end{longtable}

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}

\begin{longtable}[c]{cccccc}

\caption{Anova table of exploratory LMMs investigating the effect of block (1 vs. 2), group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings in Experiment 2.
}\label{tab:tableS9}\\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Effect}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{SS}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Df}}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{num}}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Df}}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{den}}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{F}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{p}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\endfirsthead

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Effect}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{SS}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Df}}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{num}}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{Df}}}}\fontsize{8}{8}\selectfont{\textsubscript{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{den}}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{F}}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{\textbf{p}}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Group}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{92.30}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{165.96}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.24}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.624}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Block}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{3.27}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{6,420.49}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.01}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.926}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{40,124.42}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{165.99}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{104.76}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<\ 0.001}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Group\ x\ Block}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{579.16}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{6,420.49}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1.51}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.219}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Group\ x\ Cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{2,952.91}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{165.99}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{7.71}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.006}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Block\ x\ Cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{13,155.20}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{6,445.98}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{34.35}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{<\ 0.001}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=0.5pt}-}



\multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{Group\ x\ Block\ x\ Cue}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{79.33}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{1}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{6,445.98}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}r}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.21}}}} & \multicolumn{1}{!{\color[HTML]{000000}\vrule width 0pt}>{}l!{\color[HTML]{000000}\vrule width 0pt}}{\fontsize{8}{8}\selectfont{\textcolor[HTML]{000000}{\global\setmainfont{Arial}{0.649}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}



\end{longtable}

\begin{figure}

{\centering \includegraphics[width=1950px]{supplementary_files/figure-latex/figureS3-1} 

}

\caption{Box-plot of expectancy ratings in Experiment 2 according to the group (CG vs. UG), the block (1 vs. 2) and the cue ($cue_{neg}$ vs. $cue_{neu}$). Points represent the mean estimated value for each participant and condition.}\label{fig:figureS3}
\end{figure}

\newpage

\hypertarget{trials-1}{%
\subsubsection{Trials}\label{trials-1}}

\begin{figure}

{\centering \includegraphics[width=1950px]{supplementary_files/figure-latex/figureS4-1} 

}

\caption{Relationship between trials, group (CG vs. UG) and cue ($cue_{neg}$ vs. $cue_{neu}$) on expectancy ratings for Experiment 2. On the top, for each subject and group a loess regression is fitted using the is fitted using the ggplot package and the loess method in order to represent the non-linear pattern. On the bottom, we applied the same approach at the group level. Furthermore, given the non-linearity we did not reported the linear mixed-model analysis.}\label{fig:figureS4}
\end{figure}

\hypertarget{discussion-experiment-2-exploratory-model-on-expectancy-ratings}{%
\subsection{Discussion (Experiment 2 exploratory model on expectancy ratings)}\label{discussion-experiment-2-exploratory-model-on-expectancy-ratings}}

Results of the exploratory model on expectancy ratings in Experiment 2 showed only a significant interaction between cue and block (\(F(1, 6561) = 30.76\), \(p < 0.001\)). Post-hoc contrasts decomposing the interaction showed that, regardless of group, expectancy ratings to cueneg became more negative between block 1 and block 2 (\(block 1-2: -2.69\), \(SE = 0.68\), \(t(6549) = -3.97\), \(p < 0.001\)), while expectancy ratings to cue\textsubscript{neu} became less negative from block 1 to block 2 (\(block 1-2: 2.63\), \(SE = 0.68\), \(t(6546) = 3.87\), \(p < 0.001\)).
Thus, results suggest that both groups show progressively more extreme ratings as the test phase progresses. While this trend is consistent with what might be expected (and with what was found in Experiment 1) for the UG, as they transitioned from a less reliable (50\%) to a more reliable (75\%) context, it is reversed from the expected trend (found in Experiment 1) for the CG. Speculating on the possible reason of such a different pattern of results, it could be possible that for participants in the CG (for which expectancies based on previous learnings are actually more reliable) it might be harder to adapt their expectancy ratings to a new probabilistic ratio when it draws on a different sensory modality than that involved in prior learning (as is the case in Experiment 2). Thus, they could be more resilient - and perhaps they could need more trials - to adapt their expectancies to new learnings as compared to participants in the UG, for which in both cases (same or different sensory modalities) a reliable previous experience is not available, and thus learning new contingencies may be equally easy - or may require less trials. However, this very speculative interpretation should be taken with caution, as further studies are needed to shed light on how quickly people adapt their expectancies to new contingencies within vs.~across sensory modalities.

\end{document}
